### ISSUE TITLE
submit form radio buttons

### ISSUE THREAD

**Issue by jeinglis** [enochtsang/flock-information-database#18]
How do we want to put these into the database since they relate to medications

**Comment by ExtraGravity** [comment]
Can you elaborate further please?

On that note, for the grow out density, we will convert to kg/m^2. So depending on the value of the radio button, we can convert the given number into kg/m^2 before storing it into the database.

**Comment by jackieluc** [comment]
I think he's asking how do we convert the input of a radio button to input it into the database. I think the radio buttons were made in javascript? I'm not too sure how you would get the value from that into php for a query.

**Comment by jackieluc** [comment]
Alright so i've taken a look at submit-form.php and I think we would need to just do a 

```
$_POST['question-2']
```

and it will either return a "yes" or a "no" value. Actually I'm not even sure if you can post on type="radio". But the gist of it should be like that I believe.

**Comment by ExtraGravity** [comment]
The radio buttons are not javascript, they're elements in html.

**Comment by jeinglis** [comment]
Yea I posted this before I saw the magic Enoch worked on those buttons i didn't realize they dropped down to allow you to enter the med info. The only problem that may come up is that we have disease in medication. Where we get into trouble is with the question that has you enter only a disease so it isn't attached to a med. We may have to make disease/syndrome it's own entity.

**Comment by ExtraGravity** [comment]
Well let's leave that for a different issue, this one seems to be resolved.
