### ISSUE TITLE
Current register/login not functional with php code.

### ISSUE THREAD

**Issue by jackieluc** [enochtsang/flock-information-database#19]
In the current index.php file, it does not have php code to insert the user's input into the database and "echo" some sort of feedback to the user. I added the functionality of the register into index.php and the echoing of the message from register.php. 

With the labeling for register: 

```
<tr>
    <td><label for="register_username"><b>Username<b></label></td>
    <td><input type="text" name="register_username"></td>
</tr>
<tr>
    <td><label for="register_password"><b>Password</label><b></td>
    <td><input type="password" name="register_password"></input></td>
</tr>
```

This seems to be enough to ensure that the feedback message to the user - explaining whether to pick another username or to fill all fields, or that their account is successfully created - to not occur. Also if you click the login button with valid or invalid credentials, it takes you to "login.php", which is not what we intend it to go to (we want redirectPostLogin.php in this case).

I've tried it again with:

```
<tr>
    <td><label for="username"><b>Username<b></label></td>
    <td><input type="text" name="username"></td>
</tr>
<tr>
    <td><label for="password"><b>Password</label><b></td>
    <td><input type="password" name="password"></input></td>
</tr>
```

Although, the general labeling of register and login seem to conflict, they don't. All functionality works fine and the user is able to receive feedback upon clicking the register button. The login button also takes you to redirectPostLogin.php instead of login.php as intended.

I have pushed the working index.php onto branch "nice-login-page" for further comparison.

**Comment by jackieluc** [comment]
@enochtsang

**Comment by ExtraGravity** [comment]
I think it's fine how it is actually since it's inside the register tag the name doesn't need to be specified further.
