### ISSUE TITLE
Unprofessional Title Bar

### ISSUE THREAD

**Issue by ExtraGravity** [enochtsang/flock-information-database#23]
The title bar I feel looks unprofessional and I don't know why. Suggestions?

**Comment by jeinglis** [comment]
I think it looks pretty darn good. I guess we could change the font a bit to make it look less plain. Maybe a subtle drop shadow or something?

**Comment by ExtraGravity** [comment]
Yea, all the backgrounds have a slight gradient to them which actually feels a large step from unprofessional. I'll see if I can make a drop shadow work.

**Comment by jackieluc** [comment]
Maybe the heigh of the bar is throwing it off? But I agree with the font, it does make it look a little plain.

**Comment by ExtraGravity** [comment]
We'll just leave it as is
